<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="MeltySynth" />
		<PackageReference Include="NVorbis" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SharpKind.Assets\SharpKind.Assets.csproj" />
	  <ProjectReference Include="..\SharpKind\SharpKind.csproj" />
	</ItemGroup>

</Project>
