namespace Elite.Engine.Enums
{
    public enum CommandKey
    {
        None = 0,
        Backspace = 8,
        Ctrl = 17,
        DecreaseSpeed = 191,    // '/'
        DockingComputerOn = 'C',
        DockingComputerOff = 'D',
        DistanceToPlanet = DockingComputerOff,
        Down = 'X',
        DownArrow = 40,
        ECM = 'E',
        Tab = 9,
        EnergyBomb = Tab,
        Enter = 13,
        Esc = 27,
        EscapeCapsule = Esc,
        F1 = 112,
        F2 = 113,
        F3 = 114,
        F4 = 115,
        F5 = 116,
        F6 = 117,
        F7 = 118,
        F8 = 119,
        F9 = 120,
        F10 = 121,
        F11 = 122,
        F12 = 123,
        Find = 'F',
        Fire = 'A',
        FireMissile = 'M',
        Hyperspace = 'H',
        SpaceBar = ' ',
        IncreaseSpeed = SpaceBar,
        Jump = 'J',
        Left = 188,
        LeftArrow = 37,
        No = 'N',
        Origin = 'O',
        Pause = 'P',
        Resume = 'R',
        Right = 190,
        RightArrow = 39,
        TargetMissile = 'T',
        UnarmMissile = 'U',
        Up = 'S',
        UpArrow = 38,
        Yes = 'Y',
    }
}
