namespace Elite.Engine.Enums
{
    internal enum ShipType
    {
        Sun = -2,
        Planet = -1,
        None = 0,
        Missile = 1,
        Coriolis = 2,
        EscapePod = 3,
        Alloy = 4,
        Cargo = 5,
        Boulder = 6,
        Asteroid = 7,
        Rock = 8,
        Shuttle = 9,
        Transporter = 10,
        CobraMk3 = 11,
        Python = 12,
        Boa = 13,
        Anaconda = 14,
        Hermit = 15,
        Viper = 16,
        Sidewinder = 17,
        Mamba = 18,
        Krait = 19,
        Adder = 20,
        Gecko = 21,
        CobraMk1 = 22,
        Worm = 23,
        CobraMk3Lone = 24,
        Asp2 = 25,
        PythonLone = 26,
        FerDeLance = 27,
        Moray = 28,
        Thargoid = 29,
        Tharglet = 30,
        Constrictor = 31,
        Cougar = 32,
        Dodec = 33,
    }
}