namespace Elite.Engine.Enums
{
    internal enum SHIP
    {
        SHIP_SUN = -2,
        SHIP_PLANET = -1,
        SHIP_MISSILE = 1,
        SHIP_CORIOLIS = 2,
        SHIP_ESCAPE_CAPSULE = 3,
        SHIP_ALLOY = 4,
        SHIP_CARGO = 5,
        SHIP_BOULDER = 6,
        SHIP_ASTEROID = 7,
        SHIP_ROCK = 8,
        SHIP_SHUTTLE = 9,
        SHIP_TRANSPORTER = 10,
        SHIP_COBRA3 = 11,
        SHIP_PYTHON = 12,
        SHIP_BOA = 13,
        SHIP_ANACONDA = 14,
        SHIP_HERMIT = 15,
        SHIP_VIPER = 16,
        SHIP_SIDEWINDER = 17,
        SHIP_MAMBA = 18,
        SHIP_KRAIT = 19,
        SHIP_ADDER = 20,
        SHIP_GECKO = 21,
        SHIP_COBRA1 = 22,
        SHIP_WORM = 23,
        SHIP_COBRA3_LONE = 24,
        SHIP_ASP2 = 25,
        SHIP_PYTHON_LONE = 26,
        SHIP_FER_DE_LANCE = 27,
        SHIP_MORAY = 28,
        SHIP_THARGOID = 29,
        SHIP_THARGLET = 30,
        SHIP_CONSTRICTOR = 31,
        SHIP_COUGAR = 32,
        SHIP_DODEC = 33,
    }
}