<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\useful\libs\Useful.SDL\Useful.SDL.csproj" />
    <ProjectReference Include="..\..\..\useful\test\Useful.Fakes\Useful.Fakes.csproj" />
    <ProjectReference Include="..\..\libs\EliteSharpLib\EliteSharpLib.csproj" />
  </ItemGroup>

</Project>
