<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Useful.Abstraction\Useful.Abstraction.csproj" />
    <ProjectReference Include="..\Useful.SDL\Useful.SDL.csproj" />
    <ProjectReference Include="..\Useful\Useful.csproj" />
  </ItemGroup>

</Project>
