<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\useful\libs\SharpKind.Abstraction\SharpKind.Abstraction.csproj" />
	  <ProjectReference Include="..\..\..\useful\libs\SharpKind.Assets\SharpKind.Assets.csproj" />
	  <ProjectReference Include="..\..\..\useful\libs\SharpKind.Audio\SharpKind.Audio.csproj" />
	  <ProjectReference Include="..\..\..\useful\libs\SharpKind.Input\SharpKind.Input.csproj" />
	  <ProjectReference Include="..\..\..\useful\libs\SharpKind.Graphics\SharpKind.Graphics.csproj" />
	  <ProjectReference Include="..\..\..\useful\libs\SharpKind\SharpKind.csproj" />
	</ItemGroup>

  <ItemGroup>
    <None Update="Assets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
