<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Content Remove="C:\code\github\aphawkins\elite-the-sharp-kind\elite.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Useful.Audio\Useful.Audio.csproj" />
    <ProjectReference Include="..\Useful.Controls\Useful.Controls.csproj" />
    <ProjectReference Include="..\Useful.Graphics\Useful.Graphics.csproj" />
    <ProjectReference Include="..\Useful\Useful.csproj" />
  </ItemGroup>
</Project>
