<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="MeltySynth" />
		<PackageReference Include="NVorbis" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Useful.Assets\Useful.Assets.csproj" />
	  <ProjectReference Include="..\Useful\Useful.csproj" />
	</ItemGroup>

</Project>
